### ISSUE TITLE
Option to remove docker volumes as part of clean up

### ISSUE THREAD

**Issue by rryanq** [pytest-docker-compose/pytest-docker-compose#23]
I am running:
Python: version 3.7.3
pytest-docker-compose: version 2.0.0
pytest: version 3.10.0

I haven't found a good way to remove docker volumes as part of the clean up at the end of each test. As a result, I am stuck with 3+ GB of dangling volumes after each run of my test suite which have to be manually pruned.

The best way to remove volumes from the command line would be to call `docker-compose down -v`. I have added the line `subprocess.run('docker-compose down -v', shell=True)` after the `yield` statement in my pytest-docker-compose fixture and this does actually remove the volumes correctly and the tests all pass, but then the test results appear as follows for 4 tests:

```
.E.E.E.E
...
ERROR at teardown of <test_name>
...
docker.errors.NotFound: 404 Client Error: Not Found ("No such container: 009d17a9b0c2a9d449cd63fbbc345f7a38f1ad4729a24da91e78cfabe560ba4e")
```

These errors seem to be occurring because pytest-docker-compose attempts to bring down the containers after I have already brought them down via the subprocess call. The problem is, I don't know any other way to destroy the docker volumes. If there is a way, can someone please point it out to me? @todofixthis made this comment in a recent issue but I would love to see some clarification here:

"Note that the function-scoped `docker_containers` and `docker_network_info` fixtures are still technically accessible.  Also, for non-trivial applications, you'll have to implement the code to clean up after each test, etc." (source: https://github.com/pytest-docker-compose/pytest-docker-compose/issues/3#issuecomment-435627617)

Can you provide an example in the docs of what proper clean up code looks like, specifically for this scenario where I want to remove volumes? And if this isn't currently possible, can you add an option to remove volumes on teardown?

**Comment by todofixthis** [comment]
Hi @rryanq interesting idea; thanks for bringing it up (or down, if you'll pardon the atrocious pun 😸)!

`docker-compose` is written in Python, so this should be a relatively-straightforward matter of finding the code that runs when the `-v` flag is passed to `docker-compose down`.

You should be able to add extra cleanup code by writing a fixture that wraps one of the `*_scoped_containers` fixtures, e.g.:

```python
@pytest.fixture
def containers(function_scoped_containers):
    yield function_scoped_containers

    # Additional cleanup goes here
```

We'll have to do a little experimentation to see if there are some edge cases where the containers could be brought down before the extra cleanup code can run; might need to tinker a bit to get this just right.

**Comment by RmStorm** [comment]
Wrapping the fixtures like that will do clean up before the logs are fetched from the containers. This will lead to errors I think. The line that leaves the volumes dangling is this line:
https://github.com/pytest-docker-compose/pytest-docker-compose/blob/1c0f9a50c8a7f42d054445ab218f81aebcd19fbf/src/pytest_docker_compose/__init__.py#L178
Changing it too ```docker_project.down(ImageType.none, True)``` removes volumes on container shut down.

I'm not so sure what is best here. The tests pass just fine with and without volume removal. I think we need to either add another configuration flag to the plugin or we just need to change to default to volume removal.

I think I'm more inclined to change the default to removing volumes than to add another flag. I hadn't noticed this behaviour and I think volume removal makes sense? Should this be considered a backwards incompatible change?

**Comment by rryanq** [comment]
Hello @todofixthis and @RmStorm, thank you for responding to this issue.

So at this point, I have removed the pytest-docker-compose plugin from my project because I needed to resolve this issue quickly. I decided to just call `docker-compose up` and `docker-compose down` manually in my pytest fixture. That being said, I am still interested in resolving this issue.

I know that by default, docker does not remove volumes. According to [this](https://www.tecmint.com/remove-docker-images-containers-and-volumes/) tecmint article: "By default, volumes are not removed, to prevent vital data from being deleted if there is currently no container using the volume." 

If I were to choose between changing the default to volume removal vs. adding another configuration flag, I would go with adding another configuration flag in order to conform more closely to the way that docker itself handles volume cleanup.

**Comment by vesnikos** [comment]
I will second this issue as well. 

I 've found this thread after my test-containers started failing with 'no-more-space' errors, so having a way to remove volumes is definitely something that could be useful to people.

**Comment by RmStorm** [comment]
I've added a solution in #25, you can add the flag:
```--docker-compose-remove-volumes```
to pytest and than the plugin will remove the volumes after your tests. I will merge to master later today.

Please note that due to a different PR this new version on master will require a new syntax for using pytest-docker-compose.
