### ISSUE TITLE
publish a new version on pypi

### ISSUE THREAD

**Issue by douardda** [pytest-docker-compose/pytest-docker-compose#6]
so that python 3.5 can be used easily.

Thank you

**Comment by oleksandr-yatsuk** [comment]
Hello guys, any update in this issue ?
It would be great to use the plugin with python 3.5

**Comment by todofixthis** [comment]
@maticko I have contacted you separately to arrange this.

**Comment by RmStorm** [comment]
Version 2.0.0 should be usable with python 3.5, I just published it.
